version: "4.29"
services:
  db:
    container_name: postgres_etl_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: etl_test
    ports:
      - "5432:5432"